
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: express_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/express_users?schema=public
      JWT_SECRET: your_super_secret_jwt_key
      PORT: 3000
    depends_on:
      - db
    volumes:
      - .:/app # Mount the current directory into the container for development
      - /app/node_modules # Exclude node_modules from the mount

volumes:
  pgdata:
